CREATE USER "app_user" PASSWORD 'u9M58rmC39ZASvnBBtbLaWmVcN8DTjdADNFqzK4gVRZjXnkmZErTMVyJDgw4GHvjCeNTKz4MZaAZBZzRt5ZerNMfv49a8ADsv2VQ8dgM6nbpck7unqSwxzzMPGtgFrgLJ2pgSwEh6TpT9vj5U6qBpDGMj4hdXvEZ';

CREATE SCHEMA "private";

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" FROM "app_user";
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA "private" FROM "app_user";

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "public" TO "app_user";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "private" TO "app_user";
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "public" TO "app_user";
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "private" TO "app_user";

GRANT INSERT ON "private"."users" TO "app_user";
GRANT SELECT ON "public"."users_view" TO "app_user";